# 自定义 pg_hba：放行应用连接 + 流复制连接（scram 认证）
local all all trust
host all all 0.0.0.0/0 scram-sha-256
host all all ::1/0 scram-sha-256
host replication all 0.0.0.0/0 scram-sha-256
host replication all ::1/0 scram-sha-256